local mp = require("mp")
mp.set_property("loop-file", "inf")
mp.set_property("border", "no")
mp.set_property("geometry", "40%")
mp.set_property("autofit", "100%")
mp.add_key_binding("q", "quit_on_q", function() mp.command("quit") end)
mp.add_key_binding("MBTN_MID", "quit_on_middle", function() mp.command("quit") end)
mp.add_key_binding("WHEEL_UP", "zoom_in", function() mp.command("no-osd add window-scale 0.09") end)
mp.add_key_binding("WHEEL_DOWN", "zoom_out", function() mp.command("no-osd add window-scale -0.09") end)
mp.commandv("set", "script-opts", "osc-visibility=never")
