mp.set_property("loop-file", "inf")
mp.set_property("border", "no")
mp.set_property("geometry", "40%")
mp.set_property("autofit", "100%")
mp.set_property_native("osc", "yes")
mp.add_key_binding("MBTN_MID", "quit", function() mp.command("quit") end)
mp.add_key_binding("WHEEL_UP", "zoom-in", function() mp.command("no-osd add window-scale +0.09") end)
mp.add_key_binding("WHEEL_DOWN", "zoom-out", function() mp.command("no-osd add window-scale -0.09") end)
mp.add_key_binding("ctrl+h", "osc-visibility", function() mp.command("script-binding osc/visibility") end)
mp.commandv("script-message", "osc-visibility", is_auto and "auto" or "always", 1)
